//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tema2ps.Models.DBModel.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentInfo
    {
        public int userID { get; set; }
        public int identificationNR { get; set; }
        public int groupNR { get; set; }
        public int id { get; set; }
    
        public virtual user user { get; set; }
    }
}
